"""add security qa to user"""
from alembic import op
import sqlalchemy as sa


revision = '9be76f318c61'
down_revision = 'a9c543dfcba0'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_question', sa.String(), nullable=True))
    op.add_column('users', sa.Column('security_answer', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_answer')
    op.drop_column('users', 'security_question')
    # ### end Alembic commands ###
