"""initial"""
from alembic import op
import sqlalchemy as sa


revision = 'a9c543dfcba0'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('learning_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('user_background', sa.String(), nullable=True),
    sa.Column('total_duration_days', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_plans_id'), 'learning_plans', ['id'], unique=False)
    op.create_index(op.f('ix_learning_plans_user_id'), 'learning_plans', ['user_id'], unique=False)
    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('study_minutes', sa.Integer(), nullable=True),
    sa.Column('reflection', sa.String(), nullable=True),
    sa.Column('mood_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_id'), 'check_ins', ['id'], unique=False)
    op.create_index(op.f('ix_check_ins_plan_id'), 'check_ins', ['plan_id'], unique=False)
    op.create_table('need_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('recommended_path', sa.Text(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_need_analysis_id'), 'need_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_need_analysis_plan_id'), 'need_analysis', ['plan_id'], unique=False)
    op.create_table('plan_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('milestones', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_stages_id'), 'plan_stages', ['id'], unique=False)
    op.create_index(op.f('ix_plan_stages_plan_id'), 'plan_stages', ['plan_id'], unique=False)
    op.create_table('learning_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['plan_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_methods_id'), 'learning_methods', ['id'], unique=False)
    op.create_index(op.f('ix_learning_methods_stage_id'), 'learning_methods', ['stage_id'], unique=False)
    op.create_table('learning_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('user_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['plan_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_resources_id'), 'learning_resources', ['id'], unique=False)
    op.create_index(op.f('ix_learning_resources_stage_id'), 'learning_resources', ['stage_id'], unique=False)
    op.create_table('progress_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('study_minutes', sa.Integer(), nullable=True),
    sa.Column('content_studied', sa.Text(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['plan_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_records_id'), 'progress_records', ['id'], unique=False)
    op.create_index(op.f('ix_progress_records_plan_id'), 'progress_records', ['plan_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_records_plan_id'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_id'), table_name='progress_records')
    op.drop_table('progress_records')
    op.drop_index(op.f('ix_learning_resources_stage_id'), table_name='learning_resources')
    op.drop_index(op.f('ix_learning_resources_id'), table_name='learning_resources')
    op.drop_table('learning_resources')
    op.drop_index(op.f('ix_learning_methods_stage_id'), table_name='learning_methods')
    op.drop_index(op.f('ix_learning_methods_id'), table_name='learning_methods')
    op.drop_table('learning_methods')
    op.drop_index(op.f('ix_plan_stages_plan_id'), table_name='plan_stages')
    op.drop_index(op.f('ix_plan_stages_id'), table_name='plan_stages')
    op.drop_table('plan_stages')
    op.drop_index(op.f('ix_need_analysis_plan_id'), table_name='need_analysis')
    op.drop_index(op.f('ix_need_analysis_id'), table_name='need_analysis')
    op.drop_table('need_analysis')
    op.drop_index(op.f('ix_check_ins_plan_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_learning_plans_user_id'), table_name='learning_plans')
    op.drop_index(op.f('ix_learning_plans_id'), table_name='learning_plans')
    op.drop_table('learning_plans')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
