"""add_vip_tables"""
from alembic import op
import sqlalchemy as sa


revision = 'f8e7ccfd684d'
down_revision = 'c3218e942674'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vip_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_code', sa.String(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vip_cards_card_code'), 'vip_cards', ['card_code'], unique=True)
    op.create_index(op.f('ix_vip_cards_id'), 'vip_cards', ['id'], unique=False)
    op.create_table('vip_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_vip_memberships_id'), 'vip_memberships', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vip_memberships_id'), table_name='vip_memberships')
    op.drop_table('vip_memberships')
    op.drop_index(op.f('ix_vip_cards_id'), table_name='vip_cards')
    op.drop_index(op.f('ix_vip_cards_card_code'), table_name='vip_cards')
    op.drop_table('vip_cards')
    # ### end Alembic commands ###
